POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtuaW1pIiwiaWQiOiI1ZGYwYTI4ZDc3NWJhOTIyYTQ5MmFmOTkiLCJpYXQiOjE1NzYwNTE0OTR9.lQR1fquD62TdPHIDnN-E1KfAGynhErgarRyB6eSZcPc

{
  "title": "otsikko",
  "author": "tekijä",
  "url": "urli",
  "likes": "9000"
}
